apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata: 
  name: letsencrypt
spec: 
  acme: 
    server: {{ .Values.certserver }}
    email: {{ .Values.email }}
    privateKeySecretRef: 
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          name: {{ include "blog-app.fullname" . }}