apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "blog-app.fullname" . }}
data:
  SECRET_KEY: "my-secret-key"
  MONGODB_USER: {{.Values.mongodb.auth.username}}
  MONGODB_PASSWORD: {{.Values.mongodb.auth.password}}
  DATABASE_URL_APP: "{{ .Release.Name }}-mongodb-headless:27017"

