apiVersion: v1
kind: Service
metadata:
  name: "{{ include "blog-app.fullname" . }}-service"
  labels:
    {{- include "blog-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      # protocol: TCP
      # name: http
  selector:
    {{- include "blog-app.selectorLabels" . | nindent 4 }}
