apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blogapp
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:Liz161/argo-cd.git
    targetRevision: HEAD
    path: blogapp
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true





