apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.3.0
    chart: ingress-nginx # Set this when pulling directly from a Helm repo. DO NOT set for git-hosted Helm charts.

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
