apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana
  finalizers:
  - resources-finalizer.argocd.argoproj.io
annotations:
  argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 41.7.4
    chart: kube-prometheus-stack  # Set this when pulling directly from a Helm repo. DO NOT set for git-hosted Helm charts.

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  spec:
    source:
      helm:
        valueFiles:
        - prometheus_values.yaml
        - https://gitlab.com/liz.asraf/argo-cd  
      