apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 41.7.4
    chart: kube-prometheus-stack  # Set this when pulling directly from a Helm repo. DO NOT set for git-hosted Helm charts.
    helm:
      valueFiles:
      - prometheus_values.yaml
      - git@gitlab.com:liz.asraf/argo-cd.git  

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      