# xyxbltlvjfkcgcym
alertmanager:
  config:
    global:
      smtp_smarthost: "smtp.gmail.com:465"
      smtp_auth_username: "liz161"
      smtp_from: "liz161@gmail.com"
      smtp_auth_password: "xyxbltlvjfkcgcym"
grafana:
  grafana.ini:
    smtp:
      enabled: true
      host: "smtp.gmail.com:465"
      from_address: "liz161@gmail.com"
      user: "liz161@gmail.com"
      password: "xyxbltlvjfkcgcym"
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      kubernetes.io/tls-acme: "true"
  hosts:
    - host: grafana-liz.duckdns.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: grafana-general-tls
      hosts:
        - grafana-liz.duckdns.org