apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealedsecret
  finalizers:
  - resources-finalizer.argocd.argoproj.io
annotations:
  argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 1.1.8
    chart: sealed-secrets  # Set this when pulling directly from a Helm repo. DO NOT set for git-hosted Helm charts.
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true